# Serves the FastAPI API and Streamlit dashboard (Phase 9) from
# already-trained model artifacts -- this image does NOT train anything.
# Training happens locally (needs torch/torch_geometric, and on this
# project's dev machine, Apple Silicon MPS acceleration Docker can't
# access anyway); see README "MLOps" for the full local dev setup.
FROM python:3.12-slim

# XGBoost's compiled library needs the OpenMP runtime -- the Linux
# equivalent of `brew install libomp` on macOS (see README Phase 5
# reproduction notes). Without this, importing xgboost raises
# "libgomp.so.1: cannot open shared object file".
RUN apt-get update \
    && apt-get install -y --no-install-recommends libgomp1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY docker/requirements-serve.txt .
RUN pip install --no-cache-dir -r requirements-serve.txt

COPY src/ src/
COPY app/ app/
COPY configs/ configs/

ENV PYTHONPATH=/app/src
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# data/ and models/ are mounted at runtime (docker-compose.yml), not baked
# into the image -- they're gitignored, regenerated by the local pipeline,
# and would otherwise bloat every rebuild with ~400MB of unchanged content.
EXPOSE 8010 8512
