"""Must run before numpy/torch are imported anywhere in the test suite.

On macOS, numpy's Accelerate BLAS backend and PyTorch's own thread pool are
not safely compatible when both spin up multi-threaded execution in the
same process -- running the full suite (numpy-heavy feature-engineering
tests followed by torch-based Transformer tests) reliably segfaults inside
`multi_head_attention_forward` without this. Pinning both to a single
thread avoids the conflict; it costs some speed, not correctness, and the
suite still runs in a few seconds.
"""

import os
from pathlib import Path

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("VECLIB_MAXIMUM_THREADS", "1")

# A handful of tests (the API test suite, one feature-groups schema check)
# exercise this project's actual trained models and processed dataset
# rather than a synthetic fixture -- deliberately, since that's the only
# way to catch bugs like the feature-column-order mismatch Phase 9 found.
# Those files are gitignored (regenerated by the local pipeline, not
# checked in -- see README "Reproduction"), so a fresh CI checkout won't
# have them. Skipped with a clear reason in that case rather than failing
# on a missing-file error that looks like a real bug.
ROOT = Path(__file__).resolve().parent.parent
REQUIRED_DATA_FILES = [
    ROOT / "data" / "processed" / "features.parquet",
    ROOT / "data" / "processed" / "station_metadata.parquet",
    ROOT / "models" / "baselines" / "target_pm25_h1__xgboost.joblib",
]
LOCAL_DATA_AVAILABLE = all(p.exists() for p in REQUIRED_DATA_FILES)
SKIP_REASON_NO_DATA = (
    "requires the local processed dataset + trained models "
    "(run the Phase 1-5 pipeline first; not present in a fresh CI checkout)"
)
